#config_version=6

switches:
  #Playfield Switches
    s_bumper_left:
      number:
    s_bumper_right:
      number:
    s_left_lane:
      number:
  
  #Cabinet Switches ; Switch = s_kickback, Coil = c_kickback, light = l_kickback
    s_start:
      number:
      tags: start
    s_flipper_left:
      number:
      tags: left_flipper
      #special tag for MPF

    s_flipper_right:
      number:
      tags: right_flipper
      #special tag for MPF

  #Trough Switches
    s_trough_1:
      number:
    s_trough_2:
      number:
    s_trough_3:
      number:
    s_plunger_lane:
      number: